# GitLab CI/CD 配置文件

stages:
  - test
  - analyze
  - report

variables:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  PYTHON_VERSION: "3.11"

# 缓存配置
cache:
  paths:
    - .cache/pip
    - venv/

# 测试前准备
.test_template: &test_template
  image: python:${PYTHON_VERSION}
  services:
    - redis:7-alpine
  before_script:
    - pip install --upgrade pip
    - pip install -r backend/requirements.txt
    - pip install -r backend/requirements-dev.txt
    - pip install pytest pytest-asyncio pytest-cov
  artifacts:
    when: always
    paths:
      - test_results/
      - "*.json"
      - "*.md"
    expire_in: 30 days

# 演示测试（快速验证）
demo_test:
  <<: *test_template
  stage: test
  script:
    - python3 demo_stress_test.py
  tags:
    - docker

# 基础压力测试
basic_stress_test:
  <<: *test_template
  stage: test
  script:
    - python3 stress_test.py || true
  only:
    - main
    - develop
    - merge_requests
  tags:
    - docker

# 全面压力测试
comprehensive_stress_test:
  <<: *test_template
  stage: test
  script:
    - python3 comprehensive_stress_test.py || true
  only:
    - main
    - schedules
  tags:
    - docker
  timeout: 30m

# 模块专项测试
module_stress_test:
  <<: *test_template
  stage: test
  script:
    - python3 module_specific_stress_test.py || true
  only:
    - schedules
  tags:
    - docker

# 性能分析
performance_analysis:
  <<: *test_template
  stage: analyze
  script:
    - python3 generate_test_summary.py
    - python3 generate_charts.py
    - python3 performance_validator.py
  dependencies:
    - basic_stress_test
    - comprehensive_stress_test
  artifacts:
    paths:
      - test_results/
      - charts/
      - dashboard/
    expire_in: 30 days
  tags:
    - docker

# 性能回归检测
regression_check:
  <<: *test_template
  stage: analyze
  script:
    - python3 regression_detector.py
  only:
    - merge_requests
  allow_failure: true
  tags:
    - docker

# 生成HTML报告
generate_report:
  image: python:${PYTHON_VERSION}
  stage: report
  script:
    - pip install jinja2 plotly pandas
    - python3 generate_html_report.py
  dependencies:
    - performance_analysis
  artifacts:
    paths:
      - reports/
    expire_in: 90 days
  tags:
    - docker

# 定时任务配置
scheduled_full_test:
  <<: *test_template
  stage: test
  script:
    - ./run_all_stress_tests.sh
  only:
    - schedules
  artifacts:
    paths:
      - test_results/
    expire_in: 90 days
  tags:
    - docker

# Pages部署（测试报告）
pages:
  stage: report
  script:
    - mkdir -p public
    - cp -r reports/* public/ || true
    - cp -r charts/* public/ || true
    - cp -r dashboard/* public/ || true
  artifacts:
    paths:
      - public
  only:
    - main
  dependencies:
    - generate_report
    - performance_analysis
