version: '3.8'

# KOOK消息转发系统 - 统一Docker部署配置
# 支持一键启动所有服务

services:
  # 主应用服务
  kook-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kook-forwarder
    restart: unless-stopped
    ports:
      - "9527:9527"    # FastAPI后端
      - "9528:9528"    # 图床服务
      - "5173:5173"    # 前端开发服务（可选）
    volumes:
      # 持久化数据目录
      - ./data:/app/data
      # 配置文件
      - ./backend/.env:/app/backend/.env:ro
    environment:
      # 基础配置
      - API_HOST=0.0.0.0
      - API_PORT=9527
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # 日志配置
      - LOG_LEVEL=INFO
      - LOG_RETENTION_DAYS=3
      # 图床配置
      - IMAGE_SERVER_PORT=9528
      - IMAGE_MAX_SIZE_GB=10
      - IMAGE_CLEANUP_DAYS=7
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9527/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kook-network

  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: kook-forwarder-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - kook-network

volumes:
  # 持久化卷
  redis-data:
    driver: local

networks:
  # 内部网络
  kook-network:
    driver: bridge
